only pass $id and $email if available; remove fallback to anonymousId
segment-integrations/integration-klaviyo pull request #22
Opened 2016-10-06 23:15 UTC by WesleyDRobinson

2016-10-07 20:42 UTC, hankim813 requested changes
Could you also write unit tests to make sure we test setting just userId or email and both?

Also could you write a summary of the decision made from klaviyo and our end in the PR description so we can link back for reference in the future? 

Also helpful things to include is the jira ticket if there is one.

2016-10-07 20:42 UTC, hankim813 commented on lib/mapper.js
> +  if (userId) customer_properties.$id = userId;
we don't need `userId` or `email` variables. I would just use `track.userId()`

2016-10-07 20:42 UTC, hankim813 commented on lib/mapper.js
> +  if (email) customer_properties.$email = email;
same here

2016-10-07 20:43 UTC, hankim813 commented on lib/mapper.js
> -      $id: track.userId() || track.sessionId(),
what's the reason for removing the fallback to `anonymousId` here?

2016-10-15 01:50 UTC, WesleyDRobinson commented on lib/mapper.js
> -      $id: track.userId() || track.sessionId(),
Passing a $id to Klaviyo overrides their unique-email-address enforcement so many accounts are being created tied to a single email address when we fallback to anonymousId

2016-10-15 01:51 UTC, WesleyDRobinson commented on lib/mapper.js
> -      $id: track.userId() || track.sessionId(),
logic update needs to be applied to all ecommerce events

2016-10-15 02:00 UTC, WesleyDRobinson commented on lib/mapper.js
> +  if (userId) customer_properties.$id = userId;
I can't find docs or examples for how the mapper should behave when encountering this kind of failure. Should it throw an error up for .mapper() to handle?

2016-11-10 05:57 UTC, closed without merging