ensure unique  for ordered product events
segment-integrations/integration-klaviyo pull request #23
Opened 2016-10-11 20:33 UTC by brennan

2016-10-11 23:06 UTC, hankim813 commented
@brennan hey thanks for the PR. Could you edit your PR description to describe the issue, what the fix is doing, and any links to JIRA? 

Was this a customer issue? Are there any ramifications regarding breaking changes if this change is shipped?

2016-10-12 01:45 UTC, brennan commented
@hankim813 You got it! Added some background information - let me know if you need more!

2016-10-12 20:27 UTC, hankim813 requested changes

2016-10-12 20:27 UTC, hankim813 commented on lib/mapper.js
> +    var orderId = payloads.order.properties.$event_id;
Nitpick here -- I think this would be more readable if it was:

`var orderId = track.orderId()`

2016-10-12 20:27 UTC, hankim813 commented on lib/mapper.js
> +    var orderId = payloads.order.properties.$event_id;
in fact, you might just declare this variable and use it all throughout. I see this `orderId` can be used in other places in this function

2016-10-12 20:27 UTC, hankim813 commented on lib/mapper.js
> +    if (product.productId()) {
Another nitpick, maybe we could clean this up a bit:

```
productPayload.properties.$event_id = orderId + '_' + product.productId() || product.id() || product.sku();
```

2016-10-13 21:50 UTC, brennan commented on lib/mapper.js
> +    if (product.productId()) {
Good suggestion!

2016-10-13 21:51 UTC, brennan commented on lib/mapper.js
> +    var orderId = payloads.order.properties.$event_id;
`track.orderId()` is out of scope at this point in the code, so returns "undefined"!

2016-10-13 21:55 UTC, hankim813 commented on lib/mapper.js
> +    var orderId = payloads.order.properties.$event_id;
Ahh yeah then I'd declare the variable `orderId` outside of the scope and then reference the variable where needed all throughout @brennan

2016-10-13 21:58 UTC, hankim813 commented
@brennan After my last comment, could you also push a release commit? Code is lgtm after the small nitpicks.

Adding release commit:

in `vm`
```
$ vi package.json
# bump version to release version
$ git changelog -t x.x.x
# Add nice succint, professional release note regarding what has been changed
$ git add package.json HISTORY.md
$ git commit -m 'Release x.x.x'
$ git push origin <feature- branch>
```

This makes deploying easier since I don't have to create a new PR just to cut a new release :)

2016-10-14 18:24 UTC, brennan commented on lib/mapper.js
> +    if (product.productId()) {
Looks like this logic won't work as expected, so reverted. For example, if `product.productId()` is undefined, `undefined` is coerced to a string, which is truthy. So, if `orderId` is 123 and `product.productId() is undefined, `$event_id` would evaluate to "123_undefined"!

2016-10-14 19:18 UTC, hankim813 commented
@brennan can we update `line 97` to use the variable `orderId` instead of `track.orderId()` since it's already been defined?

2016-10-20 06:21 UTC, hankim813 approved these changes

2016-10-20 06:21 UTC, merged