lock on adding to list to avoid dupes
segment-integrations/integration-klaviyo pull request #26
Opened 2016-11-09 03:56 UTC by WesleyDRobinson

this is @sperand-io on wesley's computer. upon further testing with wes, we were unable to avoid creating dupes by passing properties.$id in our add_to_list calls.

However, when we reversed the order and waited to identify (which is async) until after hearing back from the sync add_to_list endpoint, no more dupes were created. 

One other change involved here is the stripping of redundant traits. Should we include that here?

The remaining question is how to handle falling back to anonymousId (and whether we should at all).

Options:

- remove fallback outright
- make it an option
- cut 2 versions and put new users on version with no anonId fallback.

2016-11-09 20:57 UTC, hankim813 commented
@sperand-io I think we should probably save the stripping of redundant traits on a separate PR since despite that is the right way to go moving forward, probably best to just isolate this PR since it is technically "breaking" assuming Klaviyo creates custom traits for the redundant traits we are currently sending.

I though they told us to not send anonymousId? for the sake of getting this out and for least version complication, we should just make it an option and have everyone by default not fallback  but for existing users they should since that's the current behavior

2016-11-09 20:58 UTC, hankim813 requested changes

2016-11-09 20:58 UTC, hankim813 commented on lib/index.js
> +        self._identify(mapped.peopleData, fn)
I believe you should unlock in the callback of this `_identify` function. You shouldn't unlock until all operations are done with

2016-11-09 21:14 UTC, tsholmes commented
👍 to everything han said.
We should have separate PRs for the different behavior changes.
A setting is better than multiple versions, because we don't have to maintain two branches that way.

2016-11-09 21:17 UTC, tsholmes commented on lib/index.js
> +        self._identify(mapped.peopleData, fn)
If `err` is set, you should unlock immediately, and then call `fn(err)`, otherwise call `_identify`, and `_identify` unlocks at the end.

2016-11-09 22:20 UTC, sperand-io commented
Sounds great, thanks for the review! Here's the plan then to be executed in order of priority

- [ ] this PR will *only* change ordering of requests to remove susceptibility race condition— can then go out immediately
- [ ] separate PR for *optionally* falling back to anonymousId (set true for all existing users, off by default for new)
- [ ] separate PR for stripping redundant traits

2016-11-09 22:21 UTC, sperand-io commented on lib/index.js
> +        self._identify(mapped.peopleData, fn)
`add_to_list` is synchronous and identify is not, so I'm actually not even sure we need to lock, as no two requests to the addToList endpoint would ever be in contention.  @tsholmes what do you think? I can explain the situation more in person to get your recommendation if you'd prefer.

2016-11-10 05:36 UTC, sperand-io commented
Did some testing and it looks to me like the `addToList` endpoint actually does everything the `identify` one does, so it doesn't make sense to worry about the two racing at all. We can just use identify when addToList *isn't* the appropriate measure. And since it's synchronous and Klaviyo locks on the primary identifier we can get away without locking on our end as well.

2016-11-10 05:36 UTC, closed without merging